name: 'Release automation action'
description: 'Prepares the next release'
author: 'Michael Paul'
inputs:
  token:
    description: 'GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)'
    default: ${{ github.token }}
  pre-release:
    description: 'This release will be labeled as non-production ready'
    default: false
  develop-branch:
    description: 'Branch used for development and distribution'
    default: develop
  version-files:
    description: 'Files to bump with the new version'
    required: false
outputs:
  increment:
    description: 'Type of the next release (e.g. major)'
  next-version:
    description: 'Suggestion of which version should go out next'
  changelog:
    description: 'List of merged pull requests unreleased'
runs:
  using: "composite"
  steps:
    - name: Grab current version
      id: current-version
      run: echo "current-version=$(cat VERSION)" >> $GITHUB_OUTPUT
      shell: bash
    - name: Prepare release request
      id: release
      run: node '${{ github.action_path }}/dist/index.js'
      shell: bash
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_PRE-RELEASE: ${{ inputs.pre-release }}
        INPUT_DEVELOP-BRANCH: ${{ inputs.develop-branch }}
        INPUT_CURRENT-VERSION: ${{ steps.current-version.outputs.current-version }}
    - name: Bump
      run: |
        perl -i -pe 's/${{steps.current-version.outputs.current-version}}/${{steps.release.outputs.next-version}}/' VERSION ${{ inputs.version-files }}
      shell: bash
    - name: Create Pull Request
      if: steps.release.outputs.next-version != steps.current-version.outputs.current-version
      id: cpr
      uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5.0.2
      with:
        token: ${{ inputs.token }}
        base: ${{ inputs.develop-branch }}
        branch: promote/${{ inputs.develop-branch }}/to/v${{ steps.release.outputs.next-version }}
        title: Release v${{steps.release.outputs.next-version}}
        body: |
          Merged pull requests to be released:

          ${{ steps.release.outputs.changelog || '- No changes from pull requests.' }}
          
          **Full Changelog**: https://github.com/${{ github.repository }}/compare/v${{ steps.current-version.outputs.current-version }}...${{ inputs.develop-branch }}
        commit-message: "chore(release): bump to ${{steps.release.outputs.next-version}}"
        delete-branch: true
        labels: release
    - name: Enable Pull Request Automerge
      if: steps.cpr.outputs.pull-request-operation == 'created'
      uses: peter-evans/enable-pull-request-automerge@a660677d5469627102a1c1e11409dd063606628d # v3.0.0
      with:
        token: ${{ inputs.token }}
        pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
        merge-method: merge