name: Automatic Github release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - VERSION

jobs:
  github:
    permissions:
      contents: write
    uses: ./.github/workflows/reusable-github-release.yml
    with:
      release-title: Release Automation Action
      develop-branch: main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}