name: Release Automation

on:
  workflow_call:
    secrets:
      token:
        description: 'GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)'
        required: true
    inputs:
      stage:
        description: 'Prepare or publish a release'
        type: string
        required: false
        default: 'prepare'
      release-title:
        description: 'Release title prefix'
        required: true
        type: string
      develop-branch:
        description: 'Branch used for development and distribution'
        required: true
        type: string
      pre-release:
        description: "Prepare a non-production ready release"
        type: boolean
        required: false
        default: false
      separator:
        description: 'Separator between main version and pre-release version'
        default: '-beta'
        type: string
      version-files:
        description: 'Files to bump with the new version'
        required: false
        type: string

jobs:
  prepare:
    if: (inputs.stage == 'prepare') || (github.event.pull_request.merged && ! contains(github.event.pull_request.labels.*.name, 'release'))
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare the next main release
        uses: ./
        with:
          token: ${{ secrets.token }}
          develop-branch: ${{ inputs.develop-branch }}
          version-files: ${{ inputs.version-files }}
          pre-release: ${{ inputs.pre-release }}
  publish:
    if: (inputs.stage == 'publish') || (github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'release'))
    permissions:
      contents: write
    # TODO inline job instead of nesting 
    uses: ./.github/workflows/reusable-github-release.yml
    with:
      release-title: ${{ inputs.release-title }}
      develop-branch: ${{ inputs.develop-branch }}
    secrets:
      token: ${{ secrets.token }}